esphome:
  name: esp
  friendly_name: ESP

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xAb/5aOfaKy7nZZywkM2Ixgq7WhIZu9Wu9kvbiH9DYg="

ota:
  password: "8e353029a1f606e3a7482dd62f9051a8"

wifi:
  ssid: virus_distribution_center
  password: greatodinsraven

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Fallback Hotspot"
    password: "KIAulj6CuHtX"

captive_portal:
    